spring:
  application:
    name: eureka-ribbon-client
server:
  port: 8888

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:10097/eureka/

# 如果 hystrix dashboard 出现 hystrix Unable to connect to Command Metric Stream.
# 并且在 console中出现 if it should be allowed to add it to hystrix.dashboard.proxyStreamAllowList
# 则需要添加此属性
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
